services:

  agendador-tarefas:
    build:
      context: ../../../agendador-tarefas/agendador-tarefas
      dockerfile: docker/Dockerfile
    container_name: agendador-tarefas
    ports:
      - "${AGENDADOR_PORT}:8081"
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/${MONGO_DB}
    depends_on:
      - mongo

  bff-agendador-tarefas:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bff-agendador-tarefas
    ports:
      - "${BFF_PORT}:8083"
    restart: always
    environment:
      - USUARIO_URL=${USUARIO_URL}
      - AGENDADOR_TAREFAS_URL=${AGENDADOR_TAREFAS_URL}
      - NOTIFICACAO_URL=${NOTIFICACAO_URL}
    depends_on:
      - usuario
      - agendador-tarefas
      - notificacao

  usuario:
    build:
      context: ../../../usuario/usuario
      dockerfile: docker/Dockerfile
    container_name: usuario
    ports:
      - "${USUARIO_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  notificacao:
    build:
      context: ../../../notificacao/notificacao
      dockerfile: docker/Dockerfile
    container_name: notificacao
    ports:
      - "${NOTIFICACAO_PORT}:8084"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}